# Generated by Django 5.1.6 on 2025-02-26 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=10)),
                ('num_subjects', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sessions_per_day', models.IntegerField()),
                ('max_lectures', models.IntegerField()),
                ('max_practicals', models.IntegerField()),
                ('recess1_start', models.TimeField(blank=True, null=True)),
                ('recess1_end', models.TimeField(blank=True, null=True)),
                ('recess2_start', models.TimeField(blank=True, null=True)),
                ('recess2_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('weekly_lectures', models.IntegerField()),
                ('has_practical', models.BooleanField(default=False)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.timetable')),
            ],
        ),
    ]
