# Generated by Django 5.1.6 on 2025-02-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='end_time',
            new_name='college_end_time',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='start_time',
            new_name='lecture_start_time',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='recess1_end',
            new_name='recess_1_end',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='recess1_start',
            new_name='recess_1_start',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='num_subjects',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='recess2_end',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='recess2_start',
        ),
        migrations.AddField(
            model_name='timetable',
            name='fourth_year_subjects',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='timetable',
            name='second_year_subjects',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='timetable',
            name='third_year_subjects',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
