# Generated by Django 5.1.6 on 2025-02-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_end_time_timetable_college_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='department',
            field=models.CharField(max_length=255),
        ),
    ]
