# Generated by Django 5.1.6 on 2025-02-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_timetable_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
