# Generated by Django 5.1.6 on 2025-03-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_timetable_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='fourth_year_subjects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='second_year_subjects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='third_year_subjects',
            field=models.JSONField(default=list),
        ),
    ]
