# Generated by Django 5.1.6 on 2025-03-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_timetable_fourth_year_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='fourth_year_timetable',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='timetable',
            name='second_year_timetable',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='timetable',
            name='third_year_timetable',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
