# Generated by Django 5.1.6 on 2025-03-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_timetable_fourth_year_timetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('time_slot', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
