# Generated by Django 5.1.6 on 2025-03-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_teacherschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedTeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_teacher', models.CharField(max_length=100)),
                ('replacement_teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('time_slot', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
