# Generated by Django 5.1.6 on 2025-03-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_updatedteacherschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedteacherschedule',
            name='practical',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
