# Generated by Django 5.1.6 on 2025-04-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_updatedteacherschedule_practical'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='short_recess_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='short_recess_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
