# Generated by Django 5.1.6 on 2025-04-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_timetable_short_recess_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='short_recess_end',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='short_recess_start',
        ),
    ]
