# Generated by Django 5.1.6 on 2025-04-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_timetable_short_recess_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='short_recess_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='short_recess_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
