# Generated by Django 5.1.6 on 2025-05-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_timetable_short_recess_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherschedule',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
