# Generated by Django 5.1.6 on 2025-05-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_teacherschedule_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherschedule',
            name='email',
        ),
    ]
